package com.tu.FinancialQuickCheck.Controller;

import com.tu.FinancialQuickCheck.Project;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController
public class ProjectsController {

    // auto-generated by Spring, we will use it to handle data
    @Autowired
    private com.tu.FinancialQuickCheck.ProjectRepository projectRepository;

    // TODO: implement
    @GetMapping("/myprojects")
    public String[] getUserProjects(@RequestParam Integer userID) {
        String[] userprojects = {"Commerzbank", "DKB", "Some other financial institution"};
        return userprojects;
    }

    // TODO: exception handling if ID doesnt exist
    @GetMapping("/myprojects/project")
    Optional<Project> getProjectData(@RequestParam Integer projectID) {
        Optional<Project> p = projectRepository.findById(projectID);
        return p;
    }

    // TODO: check if we need the project.setID()
    @PostMapping("/myprojects/project")
    Project newProject(@RequestParam String projectName) {
        Project newProject = new Project();
        newProject.setName(projectName);
//        newProject.setId(projectName.length());
        return projectRepository.save(newProject);
    }

    // TODO: exception handling if ID doesnt exist
    @DeleteMapping("/myprojects/project")
    void deleteProject(@RequestParam Integer projectID) {
        projectRepository.deleteById(projectID);
    }

    // not part of the official contract, just to test access to mysql
    @GetMapping(path="/allprojects")
    public @ResponseBody
    Iterable<Project> getAllProjects() {
        // This returns a JSON with all users
        return projectRepository.findAll();
    }
}
