
version : '3.5'

services:
  database:
    image: "mysql:8"
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  service:
    image: "maven:3.6.3-jdk-11-slim"
    container_name: service
    command: mvn -f /app/ compile spring-boot:run
    volumes:
    - ./service:/app
    ports:
    - "8080:8080"
