version : '3.5'

services:
  database:
    image: "mysql:8"
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  service:
    image: "maven:3.6.3-jdk-11-slim"
    container_name: service
    command: mvn -f /app/ spring-boot:run
    volumes:
      - ./service/src:/app/src
      - ./service/pom.xml:/app/pom.xml
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: "frontend"
    volumes:
      - ./frontend/quickcheck:/app
    ports:
      - "3000:3000"
      - "80:3000" # just for convenience
