version : '3.5'

services:
  database:
    image: "mysql:8"
    container_name: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - ./DummyData/customconfig.cnf:/etc/mysql/conf.d/custom.cnf
      - ./DummyData/sqlfiles:/docker-entrypoint-initdb.d
    env_file: deployment.env
    expose:
      - "3306"
    ports:
      - "3306:3306"

  service:
    image: "maven:3.6.3-jdk-11-slim"
    container_name: service
    command: mvn -f /app/ spring-boot:run
    env_file: deployment.env
    volumes:
      - ./service:/app
      - ./service/pom.xml:/app/pom.xml
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    env_file: deployment.env
    ports:
      - "80:80"
    depends_on:
      - database
      - service
