version : '3.5'

# file .env is sourced for env variables by docker compose

services:
  database:
    image: "mysql:8"
    container_name: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - ./DummyData/customconfig.cnf:/etc/mysql/conf.d/custom.cnf
      - ./DummyData/sqlfiles:/docker-entrypoint-initdb.d
    env_file: database.env
    expose:
      - 3306
    ports:
      - 3306:3306

  service:
    image: "maven:3.6.3-jdk-11-slim"
    container_name: service
    command: mvn -f /app/ spring-boot:run
    volumes:
      - ./service:/app
      - ./service/pom.xml:/app/pom.xml
    ports:
      - 8080:8080
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - "API_URL=localhost:8080/"
    ports:
      - 3000:3000
    depends_on:
      - database
      - service
