INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (1, null, 'Dispokredit', null, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (2, null, 'Ratenkredit', null, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (3, null, 'Ratenkredit Standard', 2, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (4, null, 'Ratenkredit Flex', 2, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (5, null, 'Ratenkredit 3', 2, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (6, null, 'Ratenkredit 4', 2, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (7, null, 'Baufinanzierung', null, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (8, null, 'Baufinanzierung Standard', 7, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (9, null, 'Baufinanzierung Flex', 7, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (10, null, 'Baufinanzierung Nachhaltigkeit', 7, 1, 1);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (11, null, 'DUMMY', null, 1, 2);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (12, null, 'DUMMY', null, 2, 2);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (13, null, 'DUMMY', null, 3, 3);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (14, null, 'DUMMY', null, 4, 3);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (15, null, 'DUMMY', null, 5, 3);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (16, null, 'DUMMY', null, 6, 4);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (17, null, 'DUMMY', null, 1, 5);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (18, null, 'DUMMY', null, 2, 5);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (19, null, 'DUMMY', null, 3, 6);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (20, null, 'DUMMY', null, 4, 6);
