INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (100, 'some comment', 'Sichteinlagen', true, null, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (101, 'some comment', 'Termingeld, Festgeld', false, 100, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (102, null, 'Spareinlagen', true, 100, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (103, 'some comment', 'Sparbriefe', false, null, 2, 200);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (104, null, 'Pfandbriefe', true, null, 1, 300);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (105, 'some comment', 'Zertifikate', false, null, 1, 300);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (106, 'some comment', 'Bausparverträge', true, null, 2, 400);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (107, null, 'Swaps', false, null, 2, 400);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (108, 'some comment', 'Optionen', true, null, 1, 200);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (109, 'some comment', 'Versicherungen mit Anlagencharakter', false, null, 1, 400);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (110, null, 'DUMMY', null, null, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (111, null, 'DUMMY', null, null, 2, 100);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (112, null, 'DUMMY', null, null, 3, 200);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (113, null, 'DUMMY', null, null, 4, 200);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (114, null, 'DUMMY', null, null, 5, 200);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (115, null, 'DUMMY', null, null, 6, 300);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (116, null, 'DUMMY', null, null, 1, 400);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (117, null, 'DUMMY', null, null, 2, 400);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (118, null, 'DUMMY', null, null, 3, 500);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (119, null, 'DUMMY', null, null, 4, 500);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (120, null, 'DUMMY', null, null, 5, 500);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (121, null, 'DUMMY', null, null, 6, 500);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (122, null, 'DUMMY', null, null, 1, 600);
INSERT INTO bootdb.product_entity (id, comment, name, overall_rating, parent_product_id, productarea, project) VALUES (123, null, 'DUMMY', null, null, 2, 600);
