PUT localhost:8080/projects/10
Content-Type: application/json

{
  "projectName": "Update Name",
  "productAreas": [1,2,4],
  "members": [
    {
      "userID": "0fef539d-69be-4013-9380-6a12c3534c67",
      "userEmail": "lily@amos.de",
      "userName": "string",
      "role": "CLIENT"
    }
  ]
}

<> 2021-12-13T095735.200.json
<> 2021-12-13T094807.200.json
<> 2021-12-13T093227.200.json
