PUT localhost:8080/products/2/ratings
Content-Type: application/json

{
  "productName": "Termingeld, Festgeld",
  "ratings": [
    {
      "ratingID": 1,
      "answer": "new answer 1"},
    {
      "ratingID": 2,
      "comment": "new comment 2",
      "score": "HOCH"}
  ]
}


