###

# curl --location --request POST 'localhost:8080/projects'
#--header 'Content-Type: application/json'
#--data-raw '{
#  "creatorID": 1,
#  "projectName": "DKB",
#  "members": [
#    1,
#    2
#  ],
#  "productAreas": [
#    1,
#    2,
#    3
#  ]
#}'
POST localhost:8080/projects
Content-Type: application/json

{
  "creatorID": 1,
  "projectName": "DKB",
  "members": [
    1,
    2
  ],
  "productAreas": [
    1,
    2,
    3
  ]
}

###

