POST localhost:8080/projects/1/productArea/1/products
Content-Type: application/json

{
  "name": "Neue Anlagen",
  "productVariations": [
    {
      "name": "Anlagen 1"
    },
    {
      "name": "Anlagen 2"
    }
  ]
}

<> 2021-11-23T153103.500.json
