INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (1, 'Frequenz (Nachfrage) p.a.', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (2, 'Produktabschlüsse p.a.', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (3, 'Durchschnittliche Losgröße/Stückelung', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (4, 'Kreditvolumen im Bestand', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (5, 'Marge', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (6, 'Schätzung Sachaufwand', 'Aufwandsschätzung', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (7, 'Schätzung Personalaufwand', 'Aufwandsschätzung', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (8, 'Schätzung IT-Aufwand', 'Aufwandsschätzung', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (9, 'Gesamteinschätzung wirtschaftliche Bewertung', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (10, 'Wie viele unterschiedliche Produktschlüssel existieren für das Produkt Dispokredit?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (11, 'Welche Kunden (Einzelkunden/Gemeinschaftskunden) nehmen diese Produktvariante in Anspruch?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (12, 'Wie hoch ist die Anzahl abgeschlossener Kredite für die jeweiligen Produktschlüssel und wie viele entfallen davon auf Einzelkunden und Gemeinschaftskunden?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (13, 'Wie hoch ist das Volumen der abgeschlossenen Kredite für die jeweiligen Produktschlüssel und wie viele entfallen davon auf Einzelkunden und Gemeinschaftskunden?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (14, 'Wie hoch ist die Marge der abgeschlossenen Kredite für die jeweiligen Produktschlüssel? Und wie hoch ist die Marge bei den Kundengruppen Einzelkunden und Gemeinschaftskunden?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (15, 'Wie hoch ist der Deckungsbeitrag der abgeschlossenen Kredite die jeweiligen Produktschlüssel? Und wie hoch ist der Deckungsbeitrag dabei bei den Kundengruppen Einzelkunden und Gemeinschaftskunden?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (16, 'Wie ist die Verteilung des KYC-Scores (z.B. x% grün/gelb/rot) je Produktschlüssel?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (17, 'Wie hoch ist die Ablehnungsquote bei den jeweiligen Produktschlüsseln? Wie verhält sich die Ablehnungsquote bei Einzelkunden und bei Gemeinschaftskunden?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (18, 'Gesamt', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (19, 'Gibt es unterschiedliche Ratingmodelle für dieses Produkt?', 'Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (20, 'Wie viele der Produkte sind ausgefallen (historische Betrachtung)?', 'Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (21, 'Wie ist die Ausfallquote des Produkts und der jeweiligen Produktschlüssel?', 'Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (22, 'Gesamt', 'Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (23, 'Gibt es unterschiedliche Zahlungsbedingungen für das Produkt und die jeweiligen Produktschlüssel und wenn ja, welche?', 'Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (24, 'Werden unterschiedliche Zinsoptionen angeboten und wenn ja, welche? (Z.B. fixe/variable Verzinsung, Verzinsung gem. unterschiedlichen Refernezzinssätzen)', 'Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (25, 'Gibt es unterschiedliche Tilgungsoptionen für das Produkt und die jeweiligen Produktschlüssel, und wenn ja, welche?', 'Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (26, 'Gesamt', 'Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (27, 'Gibt Dokumente je Produkt und Produktschlüssel, die immer bei jeder Sicherheit eingereicht werden müssen und wenn je, welche sind das?', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (28, 'Wie viele Dokumente je Produkt und Produktschlüssel werden im Schnitt je Sicherheitenart angefordert?', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (29, 'Welche Dokumente werden je Sicherheitenart angefordert?', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (30, 'Welche Prozessschritte müssen bei der Sicherheitenbewertung durchlaufen werden?', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (31, 'Wie erfolgt die Erstellung des Sicherheitenvertrags? (Automatisiert, manuell, bestehende Textbausteine etc.)', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (32, 'Wie viele IT-Systeme werden für den gesamten Prozess der Sicherheitenbewertung, -erfassung, -freigabe etc. genutzt?', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (33, 'Gesamt', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (34, 'Wie viele unterschiedliche Kreditprozesse gibt es?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (35, 'Welche Kriterien entscheiden, über welche der vorhandenen Kreditprozess der Kredit geleitet/entschieden wird?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (36, 'Wie sind diese Kriterien definiert (z.B. nach Kreditvolumen, Kundensegment, Ratingklasse etc.)?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (37, 'Wie viele IT-Systeme/Tools werden in einem Kreditprozess angesprochen?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (38, 'Gibt es unterschiedliche Anforderungen an die Prolongation? Z.B. unterschiedliche Arten wie „vereinfachte Prolongation„, „Standardprolongation“ etc.', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (39, 'Wie wird die Einhaltung der Prolongationstermine gesteuert/getrackt?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (40, 'Wie sind die Kredit-Kompetenzstufen ausgestattet?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (41, 'Wie viele Kreditfälle werden durch Gremienentscheidungen getroffen?', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (42, 'Gesamt', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (43, 'Wie viele und welche Dokumente muss der Kunde für die Kreditprüfung einreichen?', 'Dokumentation', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (44, 'Wie viele/welche Dokumente/Nachweise müssen je Kreditprodukt vom Kunden eingereicht werden?', 'Dokumentation', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (45, 'Wie viele/welche Dokumente werden dem Kunden nach Vertragsabschluss zugesandt?', 'Dokumentation', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (46, 'Gesamt', 'Dokumentation', 1);
