INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (1, 'Frequenz', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (2, 'Produktabschlüsse', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (3, 'Durchschnittliche Losgröße', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (4, 'Kredivolumen', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (5, 'Marge', null, 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (6, 'Sachaufwand', 'Aufwandsschätzung', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (7, 'Personalaufwand', 'Aufwandsschätzung', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (8, 'IT-Aufwand', 'Aufwandsschätzung', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (9, 'Wie viele unterschiedliche Produktschlüssel existieren für das Produkt Dispokredit?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (10, 'Welche Kunden (Einzelkunden/Gemeinschaftskunden) nehmen diese Produktvariante in Anspruch?', 'Kundenstruktur', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (11, 'Frage für Kreditrating', 'Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (12, 'Frage für Kreditrating', 'Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (13, 'Frage für Zahlungsbedingungen', 'Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (14, 'Frage für Zahlungsbedingungen', 'Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (15, 'Frage für Sicherheiten', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (16, 'Frage für Sicherheiten', 'Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (17, 'Frage für Regulatorik', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (18, 'Frage für Regulatorik', 'Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (19, 'Frage für Dokumentation', 'Dokumentation', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (20, 'Frage für Dokumentation', 'Dokumentation', 1);
