INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (1, null, 'Frequenz', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (2, null, 'Produktabschlüsse', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (3, null, 'Durchschnittliche Losgröße', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (4, null, 'Kredivolumen', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (5, null, 'Marge', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (6, 'Aufwandsschätzung', 'Sachaufwand', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (7, 'Aufwandsschätzung', 'Personalaufwand', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (8, 'Aufwandsschätzung', 'IT-Aufwand', 0);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (9, 'Kundenstruktur', 'Wie viele unterschiedliche Produktschlüssel existieren für das Produkt Dispokredit?', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (10, 'Kundenstruktur', 'Welche Kunden (Einzelkunden/Gemeinschaftskunden) nehmen diese Produktvariante in Anspruch?', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (11, 'Kreditrating', 'Frage für Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (12, 'Kreditrating', 'Frage für Kreditrating', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (13, 'Zahlungsbedingungen', 'Frage für Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (14, 'Zahlungsbedingungen', 'Frage für Zahlungsbedingungen', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (15, 'Sicherheiten', 'Frage für Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (16, 'Sicherheiten', 'Frage für Sicherheiten', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (17, 'Regulatorik', 'Frage für Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (18, 'Regulatorik', 'Frage für Regulatorik', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (19, 'Dokumentation', 'Frage für Dokumentation', 1);
INSERT INTO bootdb.rating_entity (id, category, criterion, ratingarea) VALUES (20, 'Dokumentation', 'Frage für Dokumentation', 1);
