INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (100, 'Sichteinlagen', null, 1, 100);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (101, 'Termingeld, Festgeld', 100, 1, 100);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (102, 'Spareinlagen', 100, 1, 100);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (103, 'Sparbriefe', null, 2, 200);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (104, 'Pfandbriefe', null, 1, 300);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (105, 'Zertifikate', null, 1, 300);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (106, 'Bausparverträge', null, 2, 400);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (107, 'Swaps', null, 2, 400);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (108, 'Optionen', null, 1, 200);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (109, 'Versicherungen mit Anlagencharakter', null, 1, 400);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (110, 'DUMMY', null, 1, 100);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (111, 'DUMMY', null, 2, 100);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (112, 'DUMMY', null, 3, 200);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (113, 'DUMMY', null, 4, 200);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (114, 'DUMMY', null, 5, 200);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (115, 'DUMMY', null, 6, 300);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (116, 'DUMMY', null, 1, 400);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (117, 'DUMMY', null, 2, 400);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (118, 'DUMMY', null, 3, 500);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (119, 'DUMMY', null, 4, 500);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (120, 'DUMMY', null, 5, 500);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (121, 'DUMMY', null, 6, 500);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (122, 'DUMMY', null, 1, 600);
INSERT INTO bootdb.product_entity (id, name, parent_product_id, productarea, project) VALUES (123, 'DUMMY', null, 2, 600);
