INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (100, 'some comment', 'Sichteinlagen', null, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (101, 'some comment', 'Termingeld, Festgeld', 100, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (102, null, 'Spareinlagen', 100, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (103, 'some comment', 'Sparbriefe', null, 2, 200);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (104, null, 'Pfandbriefe', null, 1, 300);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (105, 'some comment', 'Zertifikate', null, 1, 300);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (106, 'some comment', 'Bausparverträge', null, 2, 400);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (107, null, 'Swaps', null, 2, 400);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (108, 'some comment', 'Optionen', null, 1, 200);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (109, 'some comment', 'Versicherungen mit Anlagencharakter', null, 1, 400);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (110, null, 'DUMMY', null, 1, 100);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (111, null, 'DUMMY', null, 2, 100);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (112, null, 'DUMMY', null, 3, 200);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (113, null, 'DUMMY', null, 4, 200);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (114, null, 'DUMMY', null, 5, 200);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (115, null, 'DUMMY', null, 6, 300);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (116, null, 'DUMMY', null, 1, 400);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (117, null, 'DUMMY', null, 2, 400);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (118, null, 'DUMMY', null, 3, 500);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (119, null, 'DUMMY', null, 4, 500);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (120, null, 'DUMMY', null, 5, 500);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (121, null, 'DUMMY', null, 6, 500);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (122, null, 'DUMMY', null, 1, 600);
INSERT INTO bootdb.product_entity (id, comment, name, parent_product_id, productarea, project) VALUES (123, null, 'DUMMY', null, 2, 600);
