openapi: '3.0.0'
info:
  version: '0.1'
  title: "API for AMOS5 Financial QuickCheck"
  description: defines endpoints for resource "Rating" and "ProductRating"

paths:
  /products/{productID}/ratings:
    get:
      summary: retrieve data for economic and/or complexity rating for projectID
      parameters:
        - $ref: '#/components/parameters/productID'
        - $ref: '#/components/parameters/ratingArea'
      responses:
        200:
          description: JSON containing all ratings for productID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getProductRating'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'  
    post:
      summary: create data for economic or complexity rating
      parameters: 
        - $ref: '#/components/parameters/productID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postProductRating'
      responses:
        201:
          description: JSON containing all ratings for productID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postProductRating'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'
    put:
      summary: updates data for economic or complexity rating
      parameters: 
        - $ref: '#/components/parameters/productID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postProductRating'
      responses:
        200:
          description: JSON containing all ratings for productID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postProductRating'
        400:
          $ref: '#/components/responses/400badrequest'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'      
          

  /ratings:
    get:
      summary: retrieve data for economic and/or complexity rating
      parameters:
        - $ref: '#/components/parameters/ratingArea'
      responses:
        200:
          description: JSON containing all ratings 
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/rating'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'

components:
  parameters:
    productID:
      in: path
      name: productID
      required: true
      schema:
        type: integer
      description: unique product ID
    ratingArea:
      in: query
      name: ratingArea
      required: false
      schema:
        type: string
        enum: [ECONOMIC, COMPLEXITY]
      description: attribute to distinguish between data for complexity and economic rating

  schemas:
    ratingID:
      type: integer
      example: 111
    answer:
      type: string
      example: "an answer to a question or the volume of an economic criterion"
    comment:
      type: string
      example: "a comment to an answer or an economic criterion"
    score:
      type: string
      enum: [ HOCH, MITTEL, GERING ]
    rating:
      type: object
      properties:
        ratingID:
          $ref: '#/components/schemas/ratingID'
        category:
          type: string
          example: "Komplexitätstreiber oder Gruppierung von Finanzkriterien"
        criterion:
          type: string
          example: "question or criterion to be analysed"
        ratingArea:
          type: string
          enum: [ ECONOMIC, COMPLEXITY ]
    overallEconomicRating:
      type: boolean
    productRating:
      type: object
      properties:
        rating:
          $ref: '#/components/schemas/rating'
        answer:
          $ref: '#/components/schemas/answer'
        comment:
          $ref: '#/components/schemas/comment'
        score:
          $ref: '#/components/schemas/score'
    reducedProductRating:
      type: object
      properties:
        ratingID:
          $ref: '#/components/schemas/ratingID'
        answer:
          $ref: '#/components/schemas/answer'
        comment:
          $ref: '#/components/schemas/comment'
        score:
          $ref: '#/components/schemas/score'
    getProductRating:
      type: object
      properties:
        productName:
          type: string
          example: "Optionen"
        overallEconomicRating:
          $ref: '#/components/schemas/overallEconomicRating'
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/productRating'
    postProductRating:
      required:
        - ratings
      type: object
      properties:
        overallEconomicRating:
          $ref: '#/components/schemas/overallEconomicRating'
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/reducedProductRating'


    
    

  responses:
    5XXserverError:
      description: Internal error
    404notfound:
      description: Resource does not exist
    403forbidden:
      description: User is not authorized to access this resource
    401unauthorized:
      description: User not authenticated
    400badrequest:
      description: Input is missing/incorrect
    genericError:
      description: Error