openapi: '3.0.0'
info:
  version: '0.1'
  title: "User API for AMOS5 Financial QuickCheck"
  description: defines endpoints for resource "User"

paths:
  /users:
    get:
      summary: retrieve list of all users
      responses:
        200:
          description: JSON containing list of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        '5XX':
          $ref: '#/components/responses/5XXserverError'
    post:
      summary: creates a new user
      requestBody:
        description: JSON containing user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        201:
          $ref: '#/components/schemas/user'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        '5XX':
          $ref: '#/components/responses/5XXserverError'
  /users/email/{email}:
    get:
      summary: retrieve user data based on email
      parameters:
        - $ref: '#/components/parameters/userEmail'
      responses:
        200:
          description: JSON containing list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'
    put:
      summary: updates user with given email adress
      parameters:
        - $ref: '#/components/parameters/userEmail'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        200:
          description: user updated successfully
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'

  /projects/{projectID}/users:
    get:
      summary: retrieve list of all users for projectID
      parameters:
        - $ref: '#/components/parameters/projectID'
      responses:
        200:
          description: JSON containing list of all users for projectID
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userProject'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'

  /projects/{projectID}/users/{userID}:
    post:
      summary: assigns user to projectID
      requestBody:
        description: JSON containing user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUserProject'
      responses:
        201:
          description: "userID successfully assigned to projectID"
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'
    put:
      summary: updates user info for projectID
      requestBody:
        description: JSON containing user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userProject'
      responses:
        200:
          $ref: '#/components/schemas/userProject'
        401:
          $ref: '#/components/responses/401unauthorized'
        403:
          $ref: '#/components/responses/403forbidden'
        404:
          $ref: '#/components/responses/404notfound'
        '5XX':
          $ref: '#/components/responses/5XXserverError'

components:
  parameters:
    userEmail:
      name: userEmail
      in: path
      required: true
      description: unique email adress
      schema:
        type: string
    projectID:
      name: projectID
      in: path
      required: true
      description: unique identifier for project entity
      schema:
        type: string

  schemas:
    user:
      type: object
      properties:
        userEmail:
          type: string
        userName:
          type: string
        userID:
          type: string
          format: uuid

    userProject:
      type: object
      required:
        - userEmail
        - userName
        - role
      properties:
        projectID:
          type: integer
        userEmail:
          type: string

        userName:
          type: string
        userID:
          type: string
          format: uuid
        role:
          type: string
          enum: [ CLIENT, PROJECT_MANAGER, ADMIN ]

    createUser:
      type: object
      required:
        - userEmail
        - userName
        - password
        - role
      properties:
        userEmail:
          type: string
        userName:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [ CLIENT, PROJECT_MANAGER, ADMIN ]

    createUserProject:
      type: object
      required:
        - role
      properties:
        role:
          type: string
          enum: [ CLIENT, PROJECT_MANAGER, ADMIN ]



  responses:
    5XXserverError:
      description: Internal error
    404notfound:
      description: Resource does not exist
    403forbidden:
      description: User is not authorized to access this resource
    401unauthorized:
      description: User not authenticated
    genericError:
      description: Error