package com.tu.FinancialQuickCheck;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ProjectsController {

    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private com.tu.FinancialQuickCheck.ProjectRepository projectRepository;

    @GetMapping("/myprojects")
    public String[] getUserProjects(@RequestParam String username) {
        String[] userprojects = {"Commerzbank", "DKB", "Some other financial institution"};
        return userprojects;
    }

    @GetMapping(path="/allprojects")
    public @ResponseBody
    Iterable<Project> getAllProjects() {
        // This returns a JSON with all users
        return projectRepository.findAll();
    }
}
